# Generated by Django 5.0.2 on 2024-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='date2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/yourDates/')),
                ('caption', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
