# Generated by Django 5.0.2 on 2024-04-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_date2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='date2',
            new_name='imgaes',
        ),
    ]
