# Generated by Django 5.0.2 on 2024-05-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='', upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='', upload_to='uploads/product/'),
        ),
    ]
